def display_is_valid() -> bool: ...
def xdisplay_is_valid() -> bool: ...
def find_available_fonts() ->  set[str] | None: ...

def Win32_GetForegroundWindow() -> int | None: ...
def Win32_SetForegroundWindow(hwnd: int) -> None: ...
def Win32_SetProcessDpiAwareness_max() -> None: ...
def Win32_SetCurrentProcessExplicitAppUserModelID(appid: str) -> None: ...
def Win32_GetCurrentProcessExplicitAppUserModelID() -> str | None: ...
