# This is generated from a compiled module, and as such is very generic
# This could be more specific. Docstrings for this module are light

from typing import Any

BOLD: int
EXTERNAL_STREAM: int
FAST_GLYPHS: int
FIXED_SIZES: int
FIXED_WIDTH: int
GLYPH_NAMES: int
HORIZONTAL: int
ITALIC: int
KERNING: int
KERNING_DEFAULT: int
KERNING_UNFITTED: int
KERNING_UNSCALED: int
LOAD_CROP_BITMAP: int
LOAD_DEFAULT: int
LOAD_FORCE_AUTOHINT: int
LOAD_IGNORE_GLOBAL_ADVANCE_WIDTH: int
LOAD_IGNORE_TRANSFORM: int
LOAD_LINEAR_DESIGN: int
LOAD_MONOCHROME: int
LOAD_NO_AUTOHINT: int
LOAD_NO_BITMAP: int
LOAD_NO_HINTING: int
LOAD_NO_RECURSE: int
LOAD_NO_SCALE: int
LOAD_PEDANTIC: int
LOAD_RENDER: int
LOAD_TARGET_LCD: int
LOAD_TARGET_LCD_V: int
LOAD_TARGET_LIGHT: int
LOAD_TARGET_MONO: int
LOAD_TARGET_NORMAL: int
LOAD_VERTICAL_LAYOUT: int
MULTIPLE_MASTERS: int
SCALABLE: int
SFNT: int
VERTICAL: int

class FT2Font:
    ascender: Any
    bbox: Any
    descender: Any
    face_flags: Any
    family_name: Any
    fname: Any
    height: Any
    max_advance_height: Any
    max_advance_width: Any
    num_charmaps: Any
    num_faces: Any
    num_fixed_sizes: Any
    num_glyphs: Any
    postscript_name: Any
    scalable: Any
    style_flags: Any
    style_name: Any
    underline_position: Any
    underline_thickness: Any
    units_per_EM: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def _get_fontmap(self, *args, **kwargs) -> Any: ...
    def clear(self, *args, **kwargs) -> Any: ...
    def draw_glyph_to_bitmap(self, *args, **kwargs) -> Any: ...
    def draw_glyphs_to_bitmap(self, *args, **kwargs) -> Any: ...
    def get_bitmap_offset(self, *args, **kwargs) -> Any: ...
    def get_char_index(self, *args, **kwargs) -> Any: ...
    def get_charmap(self, *args, **kwargs) -> Any: ...
    def get_descent(self, *args, **kwargs) -> Any: ...
    def get_glyph_name(self, *args, **kwargs) -> Any: ...
    def get_image(self, *args, **kwargs) -> Any: ...
    def get_kerning(self, *args, **kwargs) -> Any: ...
    def get_name_index(self, *args, **kwargs) -> Any: ...
    def get_num_glyphs(self, *args, **kwargs) -> Any: ...
    def get_path(self, *args, **kwargs) -> Any: ...
    def get_ps_font_info(self, *args, **kwargs) -> Any: ...
    def get_sfnt(self, *args, **kwargs) -> Any: ...
    def get_sfnt_table(self, *args, **kwargs) -> Any: ...
    def get_width_height(self, *args, **kwargs) -> Any: ...
    def get_xys(self, *args, **kwargs) -> Any: ...
    def load_char(self, *args, **kwargs) -> Any: ...
    def load_glyph(self, *args, **kwargs) -> Any: ...
    def select_charmap(self, *args, **kwargs) -> Any: ...
    def set_charmap(self, *args, **kwargs) -> Any: ...
    def set_size(self, *args, **kwargs) -> Any: ...
    def set_text(self, *args, **kwargs) -> Any: ...

class FT2Image:
    def __init__(self, *args, **kwargs) -> None: ...
    def draw_rect(self, *args, **kwargs) -> Any: ...
    def draw_rect_filled(self, *args, **kwargs) -> Any: ...
