from .artist import Artist
from .backend_bases import RendererBase
from .patches import Shadow, Wedge
from .text import Text
from .transforms import Bbox

from typing import Any

from numpy import ndarray

class Pie(Artist):
    wedges: list[Wedge]
    def __init__(
        self,
        wedges: list[Wedge],
        values: ndarray,
        normalize: bool,
        shadows: list[Shadow] | None = ...,
    ) -> None: ...
    @property
    def texts(self) -> list[list[Text]]: ...
    @property
    def values(self) -> ndarray: ...
    @property
    def fracs(self) -> ndarray: ...
    def add_texts(self, texts: list[Text]) -> None: ...
    def get_children(self) -> list[Artist]: ...
    def get_legend_handles(self) -> list[Artist]: ...
    def get_tightbbox(
        self, renderer: RendererBase | None = ...
    ) -> Bbox | None: ...
    def __getitem__(self, key: Any) -> Any: ...
