---
ci:
  autofix_prs: false
  autoupdate_schedule: 'quarterly'
exclude: |
  (?x)^(
    extern|
    subprojects/packagefiles|
    LICENSE|
    lib/matplotlib/mpl-data|
    doc/devel/gitwash|
    doc/release/prev|
    doc/api/prev|
    lib/matplotlib/tests/data/tinypages
    )
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-docstring-first
        exclude: lib/matplotlib/typing.py  # docstring used for attribute flagged by check
      - id: end-of-file-fixer
        exclude_types: [diff, svg]
      - id: mixed-line-ending
      - id: name-tests-test
        args: ["--pytest-test-first"]
      - id: no-commit-to-branch  # Default is master and main.
      - id: trailing-whitespace
        exclude_types: [diff, svg]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: fc0f09a29bb495f4a91f00266155d6282d52485d  # frozen: v1.20.2
    hooks:
      - id: mypy
        additional_dependencies:
          - pandas-stubs
          - types-pillow
          - types-python-dateutil
          - types-psutil
          - types-docutils
          - types-PyYAML
        args: ["--config-file=pyproject.toml", "lib/matplotlib"]
        files: lib/matplotlib  # Only run when files in lib/matplotlib are changed.
        pass_filenames: false
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: 6fec9b7edb08fd9989088709d864a7826dc74e80  # frozen: v0.15.12
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--fix, --show-fixes]
  - repo: https://github.com/codespell-project/codespell
    rev: 2ccb47ff45ad361a21071a7eedda4c37e6ae8c5a  # frozen: v2.4.2
    hooks:
      - id: codespell
        files: ^.*\.(py|c|cpp|h|m|md|rst|yml)$
        args:
          - "--ignore-words"
          - "ci/codespell-ignore-words.txt"
          - "--skip"
          - "doc/project/credits.rst"
  - repo: https://github.com/pycqa/isort
    rev: a333737ed43df02b18e6c95477ea1b285b3de15a  # frozen: 8.0.1
    hooks:
      - id: isort
        name: isort (python)
        files: ^galleries/tutorials/|^galleries/examples/|^galleries/plot_types/
  - repo: https://github.com/rstcheck/rstcheck
    rev: 77490ffa33bfc0928975ae3cf904219903db755d  # frozen: v6.2.5
    hooks:
      - id: rstcheck
        additional_dependencies:
          - sphinx>=1.8.1
          - tomli
  - repo: https://github.com/adrienverge/yamllint
    rev: cba56bcde1fdd01c1deb3f945e69764c291a6530  # frozen: v1.38.0
    hooks:
      - id: yamllint
        args: ["--strict", "--config-file=.yamllint.yml"]
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 13614ab716a3113145f1294ed259d9fbe5678ff3  # frozen: 0.37.1
    hooks:
      # TODO: Re-enable this when https://github.com/microsoft/azure-pipelines-vscode/issues/567 is fixed.
      # - id: check-azure-pipelines
      - id: check-dependabot
      - id: check-github-workflows
      # NOTE: If any of the below schema files need to be changed, be sure to
      # update the `ci/vendor_schemas.py` script.
      - id: check-jsonschema
        name: "Validate AppVeyor config"
        files: ^\.appveyor\.yml$
        args: ["--verbose", "--schemafile", "ci/schemas/appveyor.json"]
      - id: check-jsonschema
        name: "Validate CircleCI config"
        files: ^\.circleci/config\.yml$
        args: ["--verbose", "--schemafile", "ci/schemas/circleciconfig.json"]
      - id: check-jsonschema
        name: "Validate GitHub funding file"
        files: ^\.github/FUNDING\.yml$
        args: ["--verbose", "--schemafile", "ci/schemas/github-funding.json"]
      - id: check-jsonschema
        name: "Validate GitHub issue config"
        files: ^\.github/ISSUE_TEMPLATE/config\.yml$
        args: ["--verbose", "--schemafile", "ci/schemas/github-issue-config.json"]
      - id: check-jsonschema
        name: "Validate GitHub issue templates"
        files: ^\.github/ISSUE_TEMPLATE/.*\.yml$
        exclude: ^\.github/ISSUE_TEMPLATE/config\.yml$
        args: ["--verbose", "--schemafile", "ci/schemas/github-issue-forms.json"]
      - id: check-jsonschema
        name: "Validate CodeCov config"
        files: ^\.github/codecov\.yml$
        args: ["--verbose", "--schemafile", "ci/schemas/codecov.json"]
      - id: check-jsonschema
        name: "Validate GitHub labeler config"
        files: ^\.github/labeler\.yml$
        args: ["--verbose", "--schemafile", "ci/schemas/pull-request-labeler-5.json"]
      - id: check-jsonschema
        name: "Validate Conda environment file"
        files: ^environment\.yml$
        args: ["--verbose", "--schemafile", "ci/schemas/conda-environment.json"]
