.. This (-*- rst -*-) format file contains commonly used link targets
   and name substitutions.  It may be included in many files,
   therefore it should only contain link targets and name
   substitutions.  Try grepping for "^\.\. _" to find plausible
   candidates for this list.

.. NOTE: reST targets are
   __not_case_sensitive__, so only one target definition is needed for
   nipy, NIPY, Nipy, etc...

.. git stuff
.. _git: https://git-scm.com/
.. _github: https://github.com
.. _github help: https://help.github.com
.. _msysgit: http://code.google.com/p/msysgit/downloads/list
.. _git-osx-installer: https://code.google.com/archive/p/git-osx-installer/downloads
.. _subversion: http://subversion.tigris.org/
.. _git cheat sheet: http://cheat.errtheblog.com/s/git
.. _pro git book: https://git-scm.com/book/en/v2
.. _git svn crash course: https://git-scm.com/course/svn.html
.. _learn.github: http://learn.github.com/
.. _network graph visualizer: https://github.com/blog/39-say-hello-to-the-network-graph-visualizer
.. _git user manual: https://schacon.github.com/git/user-manual.html
.. _git tutorial: https://schacon.github.com/git/gittutorial.html
.. _git community book: https://git-scm.com/book/en/v2
.. _git ready: http://www.gitready.com/
.. _git casts: http://www.gitcasts.com/
.. _Fernando's git page: http://www.fperez.org/py4science/git.html
.. _git magic: http://www-cs-students.stanford.edu/~blynn/gitmagic/index.html
.. _git concepts: https://www.sbf5.com/~cduan/technical/git/
.. _git clone: http://schacon.github.io/git/git-clone.html
.. _git checkout: http://schacon.github.io/git/git-checkout.html
.. _git commit: http://schacon.github.io/git/git-commit.html
.. _git push: http://schacon.github.io/git/git-push.html
.. _git pull: http://schacon.github.io/git/git-pull.html
.. _git add: http://schacon.github.io/git/git-add.html
.. _git status: http://schacon.github.io/git/git-status.html
.. _git diff: http://schacon.github.io/git/git-diff.html
.. _git log: http://schacon.github.io/git/git-log.html
.. _git branch: http://schacon.github.io/git/git-branch.html
.. _git remote: http://schacon.github.io/git/git-remote.html
.. _git config: http://schacon.github.io/git/git-config.html
.. _why the -a flag?: http://gitready.com/beginner/2009/01/18/the-staging-area.html
.. _git staging area: http://gitready.com/beginner/2009/01/18/the-staging-area.html
.. _tangled working copy problem: http://2ndscale.com/rtomayko/2008/the-thing-about-git
.. _linux git workflow: http://www.mail-archive.com/dri-devel@lists.sourceforge.net/msg39091.html
.. _git parable: http://tom.preston-werner.com/2009/05/19/the-git-parable.html
.. _git foundation: http://matthew-brett.github.io/pydagogue/foundation.html

.. other stuff
.. _python: http://www.python.org

.. |emdash| unicode:: U+02014
