
add_languages('objc', native: false)
py3.extension_module(
  '_macos',
  sources: files(
    '_macos.m',
    'MPLAppDelegate.m',
    'MPLFigureCanvas.m',
    'MPLFigureManager.m',
    'MPLNavigationToolbar2.m',
    'MPLUtils.m',
  ),
  dependencies: dependency('appleframeworks', modules: 'Cocoa'),
  override_options: ['werror=true','optimization=s'],
  objc_args: [
    # Enable Objective-C ARC
    '-fobjc-arc',

    # Add Apple-suggested flags enabled by default in Xcode
    # which are not already covered by -Wall
    '-Wblock-capture-autoreleasing',
    '-Wcomma',
    '-Wconditional-uninitialized',
    '-Wdeprecated-declarations',
    '-Wdeprecated-implementations',
    '-Wdocumentation',
    '-Wduplicate-method-match',
    '-Werror=deprecated-objc-isa-usage',
    '-Werror=non-modular-include-in-framework-module',
    '-Werror=objc-root-class',
    '-Werror=return-type',
    '-Wimplicit-retain-self',
    '-Wno-arc-repeated-use-of-weak',
    '-Wno-conversion',
    '-Wno-float-conversion',
    '-Wno-four-char-constants',
    '-Wno-implicit-atomic-properties',
    '-Wno-implicit-fallthrough',
    '-Wno-missing-braces',
    '-Wno-missing-field-initializers',
    '-Wno-missing-prototypes',
    '-Wno-newline-eof',
    '-Wno-objc-interface-ivars',
    '-Wno-selector',
    '-Wno-semicolon-before-method-body',
    '-Wno-shadow',
    '-Wno-sign-conversion',
    '-Wno-strict-selector-match',
    '-Wno-trigraphs',
    '-Wno-unknown-pragmas',
    '-Wno-unused-label',
    '-Wno-unused-parameter',
    '-Wnon-modular-include-in-framework-module',
    '-Wpointer-sign',
    '-Wprotocol',
    '-Wquoted-include-in-framework-header',
    '-Wshorten-64-to-32',
    '-Wstrict-prototypes',
    '-Wundeclared-selector',
    '-Wunguarded-availability',
    '-Wunreachable-code',
  ],
  install: true,
  subdir: 'matplotlib/backends',
)
