def get_screens() -> list[tuple[int, float, float, float, float]]: ...

class FigureManager:
    def __init__(self, canvas: object, x: float = ..., y: float = ...) -> None: ...
    def _show(self) -> None: ...
    def _raise(self) -> None: ...
    def destroy(self) -> None: ...
    def _set_window_mode(self, mode: str) -> None: ...
    @staticmethod
    def set_icon(filename: str) -> None: ...
    def set_window_title(self, title: str) -> None: ...
    def get_window_title(self) -> str | None: ...
    def resize(self, width: int, height: int) -> None: ...
    def full_screen_toggle(self) -> None: ...
    def get_window_frame(self) -> tuple[float, float, float, float]: ...
    def set_window_frame(self, x: float, y: float, w: float, h: float) -> None: ...
    def get_screen_frame(self) -> tuple[float, float, float, float]: ...
    def get_window_screen_id(self) -> int: ...
    def set_window_level(self, floating: bool) -> None: ...
    def get_window_level(self) -> bool: ...
