# macOS-only native backend. Stub generated from the C types/methods in
# ``src/_macosx.m``. NOT verified with matplotlib's ``stubtest`` (the module is
# unavailable off-macOS and was not importable when this stub was written); the
# annotations, especially argument types, are best-effort.

def event_loop_is_running() -> bool: ...
def wake_on_fd_write(fd: int) -> None: ...
def stop() -> None: ...
def show() -> None: ...
def choose_save_file(
    title: str, directory: str, default_filename: str
) -> str | None: ...

class FigureCanvas:
    def update(self) -> None: ...
    def flush_events(self) -> None: ...
    def set_cursor(self, cursor: int) -> None: ...
    def set_rubberband(self, x0: int, y0: int, x1: int, y1: int) -> None: ...
    def remove_rubberband(self) -> None: ...
    def _start_event_loop(self, timeout: float = ...) -> None: ...
    def stop_event_loop(self) -> None: ...

class FigureManager:
    def _show(self) -> None: ...
    def _raise(self) -> None: ...
    def destroy(self) -> None: ...
    def _set_window_mode(self, mode: str) -> None: ...
    @staticmethod
    def set_icon(path: str) -> None: ...
    def set_window_title(self, title: str) -> None: ...
    def get_window_title(self) -> str: ...

class NavigationToolbar2:
    def set_message(self, message: str) -> None: ...

class Timer:
    def _timer_start(self, *args: object) -> None: ...
    def _timer_stop(self) -> None: ...
