import os
import types
from datetime import datetime
from enum import Enum
from functools import total_ordering
from typing import IO, Any, Protocol, Self, TypeAlias

import numpy as np
from _typeshed import ReadableBuffer, SupportsWrite

from matplotlib import _api
from matplotlib.backend_bases import FigureCanvasBase, GraphicsContextBase
from matplotlib.dviread import DviFont
from matplotlib.figure import Figure
from matplotlib.font_manager import FontPath
from matplotlib.transforms import BboxBase

from . import _backend_pdf_ps

class _SupportsPdfRepr(Protocol):
    def pdfRepr(self) -> bytes: ...

_SupportsPdfReprExt: TypeAlias = (
    _SupportsPdfRepr
    | float
    | np.floating
    | bool
    | int
    | np.integer
    | str
    | bytes
    | dict[Name | bytes, _SupportsPdfReprExt]
    | list[_SupportsPdfReprExt]
    | tuple[_SupportsPdfReprExt, ...]
    | None
    | datetime
    | BboxBase
)

_MetadataDict: TypeAlias = dict[str, str | datetime | Name]

def pdfRepr(obj: _SupportsPdfReprExt) -> bytes: ...

class Reference:
    def __init__(self, id: int) -> None: ...
    def __repr__(self) -> str: ...
    def pdfRepr(self) -> bytes: ...
    def write(
        self, contents: _SupportsPdfReprExt, file: SupportsWrite[bytes]
    ) -> None: ...

@total_ordering
class Name:
    def __init__(self, name: Self | bytes) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: Any) -> bool: ...
    def __lt__(self, other: Any) -> bool: ...
    def __hash__(self) -> int: ...
    def pdfRepr(self) -> bytes: ...

class Verbatim:
    def __init__(self, x: bytes) -> None: ...
    def pdfRepr(self) -> bytes: ...

class Op(Enum):
    close_fill_stroke = b"b"
    fill_stroke = b"B"
    fill = b"f"
    closepath = b"h"
    close_stroke = b"s"
    stroke = b"S"
    endpath = b"n"
    begin_text = b"BT"
    end_text = b"ET"
    curveto = b"c"
    rectangle = b"re"
    lineto = b"l"
    moveto = b"m"
    concat_matrix = b"cm"
    use_xobject = b"Do"
    setgray_stroke = b"G"
    setgray_nonstroke = b"g"
    setrgb_stroke = b"RG"
    setrgb_nonstroke = b"rg"
    setcolorspace_stroke = b"CS"
    setcolorspace_nonstroke = b"cs"
    setcolor_stroke = b"SCN"
    setcolor_nonstroke = b"scn"
    setdash = b"d"
    setlinejoin = b"j"
    setlinecap = b"J"
    setgstate = b"gs"
    gsave = b"q"
    grestore = b"Q"
    textpos = b"Td"
    selectfont = b"Tf"
    textmatrix = b"Tm"
    textrise = b"Ts"
    show = b"Tj"
    showkern = b"TJ"
    setlinewidth = b"w"
    clip = b"W"
    shading = b"sh"
    def pdfRepr(self) -> bytes: ...
    @classmethod
    def paint_path(cls, fill: bool, stroke: bool) -> bytes: ...

class Stream:
    def __init__(
        self,
        id: int,
        len: Reference | None,
        file: PdfFile,
        extra: dict[Name, Any] | None = None,
        png: dict[Any, Any] | None = None,
    ) -> None: ...
    def end(self) -> None: ...
    def write(self, data: bytes) -> None: ...

class PdfFile:
    def __init__(
        self,
        filename: str | os.PathLike | IO[Any],
        metadata: _MetadataDict | None = None,
    ) -> None: ...
    @property
    def dviFontInfo(self) -> dict[Name, types.SimpleNamespace]: ...
    def newPage(self, width: float, height: float) -> None: ...
    def newTextnote(
        self,
        text: _SupportsPdfReprExt,
        positionRect: list[int | float] = [-100, -100, 0, 0],
    ) -> None: ...
    def finalize(self) -> None: ...
    def write(self, data: ReadableBuffer) -> None: ...
    def output(self, *data: _SupportsPdfReprExt) -> None: ...
    def beginStream(
        self,
        id: int,
        len: Reference | None,
        extra: dict[Name, Any] | None = None,
        png: dict[Any, Any] | None = None,
    ) -> None: ...
    def endStream(self) -> None: ...
    def outputStream(
        self, ref: Reference, data: bytes, *, extra: dict[Name, Any] | None = None
    ) -> None: ...
    def fontName(self, fontprop: FontPath | str, subset: int = 0) -> Name | None: ...
    def dviFontName(self, dvifont: DviFont) -> Name: ...
    def writeFonts(self) -> None: ...
    @_api.delete_parameter("3.11", "fontfile")
    def createType1Descriptor(self, t1font, fontfile=None): ...
    def embedTTF(self, filename, subset_index, charmap): ...
    def alphaState(self, alpha): ...
    def writeExtGSTates(self): ...
    def hatchPattern(self, hatch_style): ...
    def writeHatches(self): ...
    def addGouraudTriangles(self, points, colors): ...
    def writeGouraudTriangles(self): ...
    def imageObject(self, image): ...
    def writeImages(self): ...
    def markerObject(self, path, trans, fill, stroke, lw, joinstyle, capstyle): ...
    def writeMarkers(self): ...
    def pathCollectionObject(self, gc, path, trans, padding, filled, stroked): ...
    def writePathCollectionTemplates(self): ...
    @staticmethod
    def pathOperations(path, transform, clip=None, simplify=None, sketch=None): ...
    def writePath(self, path, transform, clip=False, sketch=None): ...
    def reserveObject(self, name=""): ...
    def recordXref(self, id): ...
    def writeObject(self, object, contents): ...
    def writeXref(self): ...
    def writeInfoDict(self): ...
    def writeTrailer(self): ...

class RendererPdf(_backend_pdf_ps.RendererPDFPSBase):
    def __init__(self, file, image_dpi, height, width): ...
    def finalize(self) -> None: ...
    def check_gc(self, gc, fillcolor=None): ...
    def get_image_magnification(self): ...
    def draw_image(self, gc, x, y, im, transform=None): ...
    def draw_path(self, gc, path, transform, rgbFace=None): ...
    def draw_path_collection(
        self,
        gc,
        master_transform,
        paths,
        all_transforms,
        offsets,
        offset_trans,
        facecolors,
        edgecolors,
        linewidths,
        linestyles,
        antialiaseds,
        urls,
        offset_position,
        *,
        hatchcolors=None,
    ): ...
    def draw_markers(
        self, gc, marker_path, marker_trans, path, trans, rgbFace=None
    ): ...
    def draw_gouraud_triangles(self, gc, points, colors, trans): ...
    def draw_mathtext(self, gc, x, y, s, prop, angle): ...
    def draw_tex(self, gc, x, y, s, prop, angle, *, mtext=None): ...
    def encode_string(self, s, fonttype): ...
    def draw_text(self, gc, x, y, s, prop, angle, ismath=False, mtext=None): ...
    def new_gc(self) -> GraphicsContextPdf: ...

class GraphicsContextPdf(GraphicsContextBase):
    def __init__(self, file): ...
    def __repr__(self): ...
    def stroke(self): ...
    def fill(self, *args): ...
    def paint(self): ...
    def capstyle_cmd(self, style): ...
    def joinstyle_cmd(self, style): ...
    def linewidth_cmd(self, width): ...
    def dash_cmd(self, dashes): ...
    def alpha_cmd(self, alpha, forced, effective_alphas): ...
    def hatch_cmd(self, hatch, hatch_color, hatch_linewidth): ...
    def rgb_cmd(self, rgb): ...
    def fillcolor_cmd(self, rgb): ...
    def push(self): ...
    def pop(self): ...
    def clip_cmd(self, cliprect, clippath): ...
    def delta(self, other): ...
    def copy_properties(self, other): ...
    def finalize(self) -> None: ...

class PdfPages:
    def __init__(
        self,
        filename: str | os.PathLike | IO[Any],
        keep_empty: None = None,
        metadata: _MetadataDict | None = None,
    ) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self, exc_type: type[BaseException] | None, exc_val: object, exc_tb: object
    ) -> None: ...
    def close(self) -> None: ...
    def infodict(self) -> _MetadataDict: ...
    def savefig(
        self, figure: Figure | int | None = None, **kwargs: dict[str, Any]
    ) -> None: ...
    def get_pagecount(self) -> int: ...
    def attach_note(
        self,
        text: _SupportsPdfReprExt,
        positionRect: list[int | float] = [-100, -100, 0, 0],
    ) -> None: ...

class FigureCanvasPdf(FigureCanvasBase):
    filetypes: dict[str, str]
    def get_default_filetype(cls) -> str: ...
    def print_pdf(
        self,
        filename: PdfPages | IO[Any],
        *,
        bbox_inches_restore: list[int | float] | None = None,
        metadata: _MetadataDict | None = None,
    ) -> None: ...
    def draw(self) -> None: ...
