# codecov can find this file anywhere in the repo, so we don't need to clutter
# the root folder.
comment: false

codecov:
  notify:
    require_ci_to_pass: no

coverage:
  status:
    patch:
      default:
        target: '80'
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: failure
    project:
      default: false
      library:
        target: auto
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: failure
        paths: '!lib/.*/tests/.*'

      tests:
        target: 97.9%
        paths: 'lib/.*/tests/.*'
