#!/bin/bash

set -euo pipefail

echo travis_fold:start:Python
curl -O https://www.python.org/ftp/python/3.8.5/python-3.8.5-macosx10.9.pkg
sudo installer -package python-3.8.5-macosx10.9.pkg -target /
sudo ln -s /usr/local/bin/python3 /usr/local/bin/python
hash -r
echo travis_fold:end:Python

echo travis_fold:start:Qt4.8
curl -O https://download.qt.io/archive/qt/4.8/4.8.7/qt-opensource-mac-4.8.7.dmg
hdiutil attach qt-opensource-mac-4.8.7.dmg
sudo installer -package '/Volumes/Qt 4.8.7/packages/Qt_headers.pkg' -target /
sudo installer -package '/Volumes/Qt 4.8.7/packages/Qt_imports.pkg' -target /
sudo installer -package '/Volumes/Qt 4.8.7/packages/Qt_libraries.pkg' -target /
hdiutil detach '/Volumes/Qt 4.8.7'
echo travis_fold:end:Qt4.8

echo travis_fold:start:ccache
curl -O -L https://github.com/ccache/ccache/releases/download/v3.7.11/ccache-3.7.11.tar.xz
tar xf ccache-3.7.11.tar.xz
pushd ccache-3.7.11
./configure --prefix=/usr/local
make
make install
popd
for compiler in clang clang++ cc gcc c++ g++; do
  ln -sf ccache /usr/local/bin/$compiler
done
echo travis_fold:end:ccache

echo travis_fold:start:pkg-config
curl -O -L https://dl.bintray.com/homebrew/mirror/pkg-config-0.29.2.tar.gz
tar xf pkg-config-0.29.2.tar.gz
pushd pkg-config-0.29.2
./configure --disable-debug --prefix=/usr/local --disable-host-tool \
            --with-internal-glib --with-pc-path=/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/local/pkgconfig \
            --with-system-include-path=/usr/include
make
make install
popd
echo travis_fold:end:pkg-config

echo travis_fold:start:libpng
curl -O -L https://downloads.sourceforge.net/libpng/libpng-1.6.37.tar.xz
tar xf libpng-1.6.37.tar.xz
pushd libpng-1.6.37
./configure --disable-dependency-tracking --disable-silent-rules --prefix=/usr/local
make
make install
popd
echo travis_fold:end:libpng

echo travis_fold:start:freetype
curl -O -L https://download.savannah.gnu.org/releases/freetype/freetype-2.6.1.tar.gz
mkdir -p build
tar -x -C build -f freetype-2.6.1.tar.gz
echo travis_fold:end:freetype
