from .geo import AitoffAxes, HammerAxes, LambertAxes, MollweideAxes
from .polar import PolarAxes
from ..axes import Axes

from typing import Type

class ProjectionRegistry:
    def __init__(self) -> None: ...
    def register(self, *projections: Type[Axes]) -> None: ...
    def get_projection_class(self, name: str) -> Type[Axes]: ...
    def get_projection_names(self) -> list[str]: ...

projection_registry: ProjectionRegistry

def register_projection(cls: Type[Axes]) -> None: ...
def get_projection_class(projection: str | None = ...) -> Type[Axes]: ...
def get_projection_names() -> list[str]: ...
