---
name: "Maintenance"
on:
  # So that PRs touching the same files as the push are updated
  push:
  # So that the `dirtyLabel` is removed if conflicts are resolve
  # We recommend `pull_request_target` so that github secrets are available.
  # In `pull_request` we wouldn't be able to change labels of fork PRs
  pull_request_target:
    types: [synchronize]

permissions: {}

jobs:
  main:
    if: github.repository == 'matplotlib/matplotlib'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check if PRs have merge conflicts
        uses: eps1lon/actions-label-merge-conflict@0273be72a0bbd58fcd71d0d6c02c209b50d1e5e1  # v3.1.0
        with:
          dirtyLabel: "status: needs rebase"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          retryMax: 10
