---
name: 'Close inactive issues'
on:
  schedule:
    - cron: '30 1 * * 2,4,6'

permissions: {}

jobs:
  stale:
    if: github.repository == 'matplotlib/matplotlib'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/stale@eb5cf3af3ac0a1aa4c9c45633dd1ae542a27a899  # v10.3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          operations-per-run: 300
          days-before-stale: -1
          stale-pr-label: "status: inactive"
          days-before-pr-close: -1
          stale-issue-label: "status: inactive"
          close-issue-label: "status: closed as inactive"
          days-before-issue-close: 30
          ascending: true
          exempt-issue-labels: "keep,status: confirmed bug"
          exempt-pr-labels: "keep,status: orphaned PR"
