---
name: Build wasm wheels

on:
  # Save CI by only running this on release branches or tags.
  push:
    branches:
      - main
      - v[0-9]+.[0-9]+.x
    tags:
      - v*
  # Also allow running this action on PRs if requested by applying the
  # "Run cibuildwheel" label.
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled

permissions:
  contents: read

jobs:
  build_wasm:
    if: >-
      (
        github.event_name == 'push' ||
        github.event_name == 'pull_request' && (
          (
            github.event.action == 'labeled' &&
            github.event.label.name == 'CI: Run cibuildwheel'
          ) ||
          contains(github.event.pull_request.labels.*.name,
                   'CI: Run cibuildwheel')
        )
      )
    name: Build wasm
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        name: Install Python
        with:
          python-version: '3.13'

      - name: Build wheels for wasm
        uses: pypa/cibuildwheel@8d2b08b68458a16aeb24b64e68a09ab1c8e82084  # v3.4.1
        env:
          CIBW_BUILD: "cp312-*"
          CIBW_PLATFORM: "pyodide"
          CIBW_TEST_COMMAND: "true"

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: cibw-wheels-wasm
          path: ./wheelhouse/*.whl
          if-no-files-found: error
